image: python:3.6

stages: [deploy]

deploy:
 stage: deploy
 only:
  - /^v\d+\.\d+\.\d+$/
 except: [branches]
 before_script:
   - pip3 install requirements.txt
 script:
   - python3 setup.py sdist bdist_wheel
   - twine upload dist/*
